server:
  # todo make a docker image
  port: 8888

spring:
  application:
    name: leaf-server
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request

# Dubbo Config properties
dubbo:
  ## Base packages to scan Dubbo Component：@com.alibaba.dubbo.config.annotation.Service
  scan:
    basePackages: com.sankuai.inf.leaf.api
  ## ApplicationConfig Bean
  application:
    id: leaf-server
    name: leaf-server
    qos-port: 22222
    qos-enable: true
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12346
    status: server

  ## RegistryConfig Bean
  registry:
    id: zookeeper
    # todo 环境变量
    address: zookeeper://192.168.47.133:2181?backup=192.168.47.133:2182,192.168.47.133:2183
  provider:
    loadbalance: roundrobin

# Enables Dubbo All Endpoints
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        ## StatusChecker Name extras (default : empty )
        extras: load,threadpool